### ISSUE TITLE
Reproduce the results using desom_benchmark.py

### ISSUE THREAD

**Issue by heitorrapela** [FlorentF9/DESOM#4]
Hello,

It is not the first time that I have tried to reproduce the experiments of this repo using the default commands provided. I uncommented all datasets on desom_benchmark.py and changed the runs to 10.

![image](https://user-images.githubusercontent.com/14017613/137034710-f219eb63-3d00-4c83-a3a3-6fc778fac162.png)

[desom_benchmark.csv](https://github.com/FlorentF9/DESOM/files/7333359/desom_benchmark.csv)

I don't know if it is a problem because I am running on CPU,

Best Regards,

**Comment by heitorrapela** [comment]
You also need to change the parameter iterations to 10k (iterations = 10000)

**Comment by FlorentF9** [comment]
Thanks a lot Heitor for your inputs, I'm lacking time to look into it for the moment, but I will come back to your issues later!

**Comment by heitorrapela** [comment]
Thanks for your feedback @FlorentF9!

**Comment by heitorrapela** [comment]
Results with iterations=10k & n_run=10 for 8x8, and 10x1 for the four datasets

[desom_benchmark.csv](https://github.com/FlorentF9/DESOM/files/7598510/desom_benchmark.csv)


![image](https://user-images.githubusercontent.com/14017613/143306972-ff609b51-f9cb-43ee-887c-6f1cfc6fb378.png)

There are some minor variations when comparing with the results of this paper: https://florentfo.rest/files/ESANN-2019-DeepEmbeddedSOM-full-paper.pdf

I guess it is because of the initialization; when you get mean & dev without fixing seeds in each run, you can't reproduce the same result, but the results were similar. :)

**Comment by KleinYuan** [comment]
@heitorrapela what change did you make to get 0.3 to 0.9 ? I also met the same issue here.

**Comment by heitorrapela** [comment]
@KleinYuan hello, it is been so long that I dont remember exactly, but following my previous comments, it is related to the versions of the libs, seeds, and I remember to play with the train/val/test split but I am not 100% sure.
